# Generated by Django 4.2.7 on 2023-11-26 18:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("imagegenerator", "0001_initial"),
    ]

    operations = []
